### PR TITLE
Expand Type field in control messages

### PR DESCRIPTION
**Pull request by LPardue**
Fixes https://github.com/moq-wg/moq-transport/issues/537

### CODE REVIEW

**Review by ianswett — APPROVED** [review]
Thanks!

**Comment by suhasHere** [comment]
Since a control message is defined as 
```
MOQT Control Message {
  Message Type (i),
  Message Payload (b),
}
```

I think we also need explicit length field for the entire message. May be we should do both the changes together ??

**Comment by LPardue** [comment]
Yes! I didn't realise that until I started on https://github.com/moq-wg/moq-transport/pull/544. And I did the work there. Whatever is the easiest to merge first, I can rebate or respin the PRs so we have full expansion in the next draft release

**Comment by suhasHere** [comment]
@LPardue yeah .. That was one of the reasons made be think that we should combine this and #544 as on pass on control message

**Review by fluffy — APPROVED** [review]
Seems good to me.

**Comment by LPardue** [comment]
closing in favor of the mega PR that people asked for: https://github.com/moq-wg/moq-transport/pull/550

**Pull request closed without merging**
