### PR TITLE
Make Datagram mode as REQUIRED

### PR DESCRIPTION
**Pull request by suhasHere**
Addresses #359

### CODE REVIEW

**Review by fluffy — APPROVED** [review]
LGTM

**Comment by kixcord** [comment]
We should have some text on what to do if the datagram extension is not negotiated.

**Comment by afrind** [comment]
> We should have some text on what to do if the datagram extension is not negotiated.

Do you want a behavior other than "all datagrams will be dropped"?  We could have the publisher reply with SUBSCRIBE ERROR.

**Comment by suhasHere** [comment]
Datagram is object preference like the other one. I don't understand the meaning of not being negotiated. The same rule applies to all the object preferences and if we want to say something then we need to add it in general section.

**Comment by afrind** [comment]
> I don't understand the meaning of not being negotiated.

I think Luke meant if the QUIC Datagram extension is not negotiated.  I believe it's required for WebTransport, but for raw QUIC the peer may not advertise support.  We could also require it for MoQ also just simply fail the entire MoQ connection without datagrams.

**Comment by suhasHere** [comment]
> > I don't understand the meaning of not being negotiated.
> 
> I think Luke meant if the QUIC Datagram extension is not negotiated. I believe it's required for WebTransport, but for raw QUIC the peer may not advertise support. We could also require it for MoQ also just simply fail the entire MoQ connection without datagrams.

Ah thanks for the clarification.  Makes sense , but I also wonder if that would be in its own PR as it is not specific to object preference. Thoughts ?

**Comment by kixelated** [comment]
> > > I don't understand the meaning of not being negotiated.
> > 
> > 
> > I think Luke meant if the QUIC Datagram extension is not negotiated. I believe it's required for WebTransport, but for raw QUIC the peer may not advertise support. We could also require it for MoQ also just simply fail the entire MoQ connection without datagrams.
> 
> Ah thanks for the clarification. Makes sense , but I also wonder if that would be in its own PR as it is not specific to object preference. Thoughts ?

I think we should make the datagram extension required as part of this PR.

The PREFER_DATAGRAM message over streams was a fallback when datagrams are not supported. By removing that fallback, we're in a state where servers and clients might silently drop all datagrams which is no bueno.

@ianswett we should have a section in connection establishment section that requires datagram support.

**Comment by afrind** [comment]
Here's the text from WebTransport if we want to copy it:

```
WebTransport over HTTP/3 also requires support for QUIC datagrams. To indicate support, both the client and the server MUST send a max_datagram_frame_size transport parameter with a value greater than 0 (see Section 3 of [QUIC-DATAGRAM]).
```

**Comment by ianswett** [comment]
I wrote #384 to require DATAGRAM support when using QUIC directly.

**Review by ianswett — APPROVED** [review]

**Pull request merged**
