### PR TITLE
Replace x(f) notation with 8-bit field

### PR DESCRIPTION
**Pull request by LPardue**
This is a proposal to illustrate the changes needed to address one aspect of https://github.com/moq-wg/moq-transport/issues/536 .

In creating this, I explicitly didn't state copy the normative action on dealing with a 0 or 1 value.  See https://github.com/moq-wg/moq-transport/issues/542 for that.

### CODE REVIEW

**Review by ianswett — APPROVED** [review]
This change seems small and sensible, especially since every time I see (f) I think it's a float, not a flag.

**Review by suhasHere — APPROVED** [review]

**Comment by martinduke** [comment]
9/25 interim: No objections to this direction, but make it MUST close if not 0 or 1. @ianswett can merge when he's satisfied the discussion has completed.

**Review by fluffy — APPROVED** [review]
Don't feel strongly one way or the other but this looks good to me.

**Comment by ianswett** [comment]
I updated this to use MUST.

**Pull request merged**
